# Generated by Django 4.0.4 on 2022-08-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserName',
            field=models.CharField(default='', max_length=25),
        ),
    ]
